api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    title: 'SAD API'
    description: 'API de sea of death'
    version: '0.1'